
name: Push

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # SET UP
      - name: Check Out
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # BUILD
      - name: Build Project
        run: ./gradlew --warn --console=plain build

      - name: Upload Tests Reports (ON FAILURE)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test_reports
          path: "*/build/**/TEST-*.xml"
